### ISSUE TITLE
Bug Report - Emoji command is not working

### ISSUE THREAD

**Issue by Nefomemes** [Nefomemes/Kylebot#22]
**Describe the bug**
The emoji command is not working. This seems to be caused by the getEmojiFromMention util function.

**To Reproduce**
1. Run the emoji

**Expected behavior**
Information and resized image of the emoji should be sent.

**Actual behavior**
Error.

**Screenshots**
![Screenshot_20201017-215934_Discord.jpg](https://user-images.githubusercontent.com/66000635/96343397-1660a900-10c4-11eb-9db8-406cca7a045a.jpg)

**Version**
Internal Alpha 0.0.4

**Why this is a bug on our end?**
The error seems to be located at the getEmojiFromMention util function. Which is my code smh.

**Additional context**
```
TypeError: Cannot read property '2' of null
    at Object.getEmojiFromMention (/home/runner/Kylebot-IA/assets/utils.js:142:70)
    at Object.module.exports.run (/home/runner/Kylebot-IA/commands/server-thingies/emoji.js:3:22)
    at Client.handleMessage (/home/runner/Kylebot-IA/events/utils/handler.js:97:19)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/runner/Kylebot-IA/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Kylebot-IA/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Kylebot-IA/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/runner/Kylebot-IA/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/runner/Kylebot-IA/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/runner/Kylebot-IA/node_modules/ws/lib/event-target.js:125:16)
```

**Comment by pani7777** [comment]
wtf discord light mode

**Comment by Nefomemes** [comment]
> wtf discord light mode

Ugh, accessibility reasons. My eyes can't stand in dark mode.

**Comment by Nefomemes** [comment]
Fixed.
