### ISSUE TITLE
Bug Report - The bot does not send a log message when a user joined.

### ISSUE THREAD

**Issue by Nefomemes** [Nefomemes/Kylebot#27]
**Describe the bug**
The bot does not send a log message when a user joined.

**To Reproduce**
1. Join a server that have configured the welcome message feature. 

**Expected behavior**
There will be a message popping up in the configured welcome log channel.

**Screenshots**
![](https://nefomemes.is-inside.me/BX94e76K.png)

**Version**
0.0.4 Production

**Additional context**
That's all we know.

**Comment by Nefomemes** [comment]
Found the error:
```
TypeError: items.filter is not a function
    at Object.getItem (/home/runner/Kylebot-IA/assets/utils.js:75:28)
    at Client.module.exports (/home/runner/Kylebot-IA/events/guildMemberAdd.js:15:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Nefomemes** [comment]
This also affects things that uses the `getItem` built-in function.

**Comment by Nefomemes** [comment]
Alright, it have been fixed.
![](https://nefomemes.is-inside.me/wC7KkQNe.png)
