### ISSUE TITLE
Bug Report - An error will appear when trying to provide the bot with id instead of a mention

### ISSUE THREAD

**Issue by Nefomemes** [Nefomemes/Kylebot#28]
**Describe the bug**
An error will appear when trying to provide the bot with id instead of a mention. This was caused by the option being a number. This is an **intended** behavior in the *argv-parsing* kind of stuff. It just the built-in functions that doesn't parse number into string.

**To Reproduce**
1. Run a command that uses id kind of stuff. Like kick, ban, or warn with an id instead of mention.

**Expected behavior**
Run as usual.

**Actual behavior**
An error appeared.

**Screenshots**
![](https://nefomemes.is-inside.me/tkocsBJu.png)

**Version**
0.0.4 Production

Vanilla branches:
`master` - Main bot.
`internal-alpha` - Testing bot.
You can also use other branches we have on the repo.

Self-hosts / forks:
Providing version and branch (that it's synced to) is optional. You can provide the source code of the self-host / fork version though.

**Why is this a bug?**
Tell more on why is this a bug on our code. It's optional though.

**Additional context**
```
TypeError: mention.startsWith is not a function
    at Object.getChannelFromMention (/home/runner/Kylebot/assets/utils.js:37:17)
    at Object.run (/home/runner/Kylebot/supcommands/configs/welcomechannel.js:6:31)
    at Client.handleMessage (/home/runner/Kylebot/events/utils/handler.js:102:19)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (/home/runner/Kylebot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/runner/Kylebot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/runner/Kylebot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/runner/Kylebot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/runner/Kylebot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/runner/Kylebot/node_modules/ws/lib/event-target.js:125:16)
```

**Comment by Nefomemes** [comment]
Found the error:
```
TypeError: items.filter is not a function
    at Object.getItem (/home/runner/Kylebot-IA/assets/utils.js:75:28)
    at Client.module.exports (/home/runner/Kylebot-IA/events/guildMemberAdd.js:15:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Nefomemes** [comment]
It now works but your profile only.

![](https://nefomemes.is-inside.me/yxN126jG.png)

**Comment by Nefomemes** [comment]
Sorry, I accidentally clicked that.

**Comment by Nefomemes** [comment]
```
DiscordAPIError: Unknown User
    at RequestHandler.execute (/home/runner/Kylebot-IA/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  method: 'get',
  path: '/users/526672758994894850',
  code: 10013,
  httpStatus: 404
}
```
This is weird.

**Comment by Nefomemes** [comment]
Fixed. It's API issue.
